version: "3"

services:
  service:
    build: ./src/service
    volumes:
      - ./src/service:/app
    ports:
      - "3000:3000"
      - "7000:7000"
    command: npm run debug
  web:
    build: ./src/web
    volumes:
      - ./src/web:/app
    ports:
      - "3001:3001"
      - "7001:7001"
